import { z } from 'zod';

export const saleItemInputSchema = z.object({
  variantId: z.string().cuid(),
  quantity: z.number().int().positive(),
  unitPrice: z.number().nonnegative(),
  discountAmount: z.number().nonnegative().default(0),
});

export const paymentInputSchema = z.object({
  method: z.enum(['CASH', 'CARD']),
  amount: z.number().positive(),
  reference: z.string().trim().max(120).optional(),
});

export const createSaleSchema = z.object({
  body: z.object({
    branchId: z.string().cuid(),
    customerId: z.string().cuid().optional(),
    items: z.array(saleItemInputSchema).min(1, 'Sale must have at least one item'),
    payments: z.array(paymentInputSchema).min(1, 'Sale must have at least one payment'),
    discountAmount: z.number().nonnegative().default(0),
    clientRequestId: z
      .string()
      .uuid()
      .describe('Idempotency key generated by the POS client to prevent duplicate sales on retry'),
  }),
});

export const cancelSaleSchema = z.object({
  params: z.object({ saleId: z.string().cuid() }),
  body: z.object({ reason: z.string().trim().min(2).max(300) }),
});

export const createReturnSchema = z.object({
  body: z.object({
    saleId: z.string().cuid(),
    branchId: z.string().cuid(),
    items: z
      .array(
        z.object({
          saleItemId: z.string().cuid(),
          quantity: z.number().int().positive(),
        }),
      )
      .min(1),
    reason: z.string().trim().min(2).max(300),
  }),
});

export const listSalesQuerySchema = z.object({
  query: z.object({
    branchId: z.string().cuid().optional(),
    from: z.coerce.date().optional(),
    to: z.coerce.date().optional(),
    page: z.coerce.number().int().positive().default(1),
    pageSize: z.coerce.number().int().positive().max(200).default(25),
  }),
});
